import './js/header';
import './js/hero';
import './js/about';
import './js/advantages';
import './js/services';
import './js/steps';
import './js/advice';
import './js/contact';
import './js/footer';
